### ISSUE TITLE
Create an abstract "Entity" model

### ISSUE THREAD

**Issue by amaurymartiny** [chronoscio/backend#22]
Roughly following [CIDOC](http://www.cidoc-crm.org/Version/version-6.2), we could create an abstract model called "Entity", which would have the following fields:

- name
- slug
- wikipedia_link
- territories

Then PoliticalEntity would inherit that with the additional requirements:
- color field
- possible DiplomaticRelations with other PoliticalEntity
- constraint on territories to be Polygon or MultiPolygon

In the future, Actor would inherit Entity with:
- SomeLink with other Actor(s)
- constraint on territories to be a Point

Event would inherit from Entity with:
- SomeOtherLink with Actor(s)
- contraint on territories to be a Point.

For now, only Entity and PoliticalEntity would be created.

**Comment by wtokumaru** [comment]
How does abstraction compare to the Nation/Territory/DiploaticRelation categorization?

**Comment by amaurymartiny** [comment]
- Entity is an abstract class above PoliticalEntity, Event and Person.
- Each Entity has 1..n Territories.
- Each PoliticalEntity has 0..n DiplomaticRelations with 0..n other PoliticalEntities. Whether to extend DipRel to the whole Entity abtract class is being discussed in #26.
