### ISSUE TITLE
Use geobuf to compress geojsons

### ISSUE THREAD

**Issue by amaurymartiny** [chronoscio/backend#38]
from @dwaxe 

I noticed this problem when I made the first version of this backend -- the shape downloads are extremely slow. Even if we cache territories upon map movement, the initial load will be unbearably slow.

To deal with that, we might want to consider geobuf (https://github.com/mapbox/geobuf) or something similar + compressing the response.

**Comment by ataalik** [comment]
There is also this library that is used in simplifying geojson: https://github.com/topojson/topojson
Although geobuf seems more up to the task we could test both before deciding on which one to use.

**Comment by amaurymartiny** [comment]
Yes, that'd be really good.

**Comment by whirish** [comment]
According to the [pygeobuf](https://github.com/pygeobuf/pygeobuf) page, geobuf is more heavily compressed than TopoJSON.

**Comment by ataalik** [comment]
Yeah it seems like it. It seems Topojson only simplifies as opposed to Geobuf actually compressing.

**Comment by ataalik** [comment]
Soo I've started on this. pygeobuff creates a bytes object. How should we encode this data. We can just return the hex values as a string. Or we could base 64 encode it but that would make it bigger in size.

**Comment by whirish** [comment]
@ataalik Hex would be fine if it's smaller.
